const { DataTypes } = require("sequelize");

module.exports = model;

function model(sequelize) {
  const attributes = {
    // Id: {
    //   type: DataTypes.INTEGER,
    //   allowNull: true,
    //   autoIncrement: true,
    //   primaryKey: true,
    // },
    priority :{type: DataTypes.STRING(225) , allowNull: true},
    ks_frccode :{type: DataTypes.STRING(225) , allowNull: true},
    ks_krasts :{type: DataTypes.STRING(225) , allowNull: true},
    ks_pttsts :{type: DataTypes.STRING(225) , allowNull: true},
    ks_krarem :{type: DataTypes.STRING(225) , allowNull: true},
    form_sts :{type: DataTypes.STRING(225) , allowNull: true},
    ucc :{type: DataTypes.STRING(225) , allowNull: true},
    kslucc :{type: DataTypes.STRING(225) , allowNull: true},
    clname :{type: DataTypes.STRING(225) , allowNull: true},
    es_catg :{type: DataTypes.STRING(225) , allowNull: true},
    ks_panno :{type: DataTypes.STRING(225) , allowNull: true},
    locnid :{type: DataTypes.STRING(225) , allowNull: true},
    ks_emailid :{type: DataTypes.STRING(225) , allowNull: true},
    es_email :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_email :{type: DataTypes.STRING(225) , allowNull: true},
    bo_email :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_esboem :{type: DataTypes.STRING(225) , allowNull: true},
    ks_mobile :{type: DataTypes.STRING(225) , allowNull: true},
    es_mobile :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_mobile :{type: DataTypes.STRING(225) , allowNull: true},
    bo_mobile :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_esbomo :{type: DataTypes.STRING(225) , allowNull: true},
    locationid :{type: DataTypes.STRING(225) , allowNull: true},
    es_locncd :{type: DataTypes.STRING(225) , allowNull: true},
    es_locnid :{type: DataTypes.STRING(225) , allowNull: true},
    neoid :{type: DataTypes.STRING(225) , allowNull: true},
    odinid :{type: DataTypes.STRING(225) , allowNull: true},
    bossid :{type: DataTypes.STRING(225) , allowNull: true},
    ks_nsecm :{type: DataTypes.STRING(225) , allowNull: true},
    ensecm :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_nsecm :{type: DataTypes.STRING(225) , allowNull: true},
    bo_nsecm :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_boncm :{type: DataTypes.STRING(225) , allowNull: true},
    ks_bsecm :{type: DataTypes.STRING(225) , allowNull: true},
    ebsecm :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_bsecm :{type: DataTypes.STRING(225) , allowNull: true},
    bo_bsecm :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_bobcm :{type: DataTypes.STRING(225) , allowNull: true},
    ks_nsefo :{type: DataTypes.STRING(225) , allowNull: true},
    ensefo :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_nsefo :{type: DataTypes.STRING(225) , allowNull: true},
    bo_nsefo :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_bonfo :{type: DataTypes.STRING(225) , allowNull: true},
    ks_nsecds :{type: DataTypes.STRING(225) , allowNull: true},
    ensecds :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_nsecds :{type: DataTypes.STRING(225) , allowNull: true},
    bo_nsecds :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_boncds :{type: DataTypes.STRING(225) , allowNull: true},
    ks_mcx :{type: DataTypes.STRING(225) , allowNull: true},
    emcx :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_mcx :{type: DataTypes.STRING(225) , allowNull: true},
    bo_mcx :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_bomcx :{type: DataTypes.STRING(225) , allowNull: true},
    ks_ncdex :{type: DataTypes.STRING(225) , allowNull: true},
    encdex :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_ncdx :{type: DataTypes.STRING(225) , allowNull: true},
    bo_ncdex :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_boncdx :{type: DataTypes.STRING(225) , allowNull: true},
    ks_nomn :{type: DataTypes.STRING(225) , allowNull: true},
    ks_nompan :{type: DataTypes.STRING(225) , allowNull: true},
    ks_nomshr :{type: DataTypes.STRING(225) , allowNull: true},
    ks_relwapc :{type: DataTypes.STRING(225) , allowNull: true},
    es_nomn :{type: DataTypes.STRING(225) , allowNull: true},
    es_nompan :{type: DataTypes.STRING(225) , allowNull: true},
    es_nomshr :{type: DataTypes.STRING(225) , allowNull: true},
    es_relwapc :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_nomn :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_cmbkg :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_fobkg :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_combkg :{type: DataTypes.STRING(225) , allowNull: true},
    mtc_cdsbkg :{type: DataTypes.STRING(225) , allowNull: true},
    coradd1 :{type: DataTypes.STRING(225) , allowNull: true},
    coradd2 :{type: DataTypes.STRING(225) , allowNull: true},
    coradd3 :{type: DataTypes.STRING(225) , allowNull: true},
    coradd4 :{type: DataTypes.STRING(225) , allowNull: true},
    corcity :{type: DataTypes.STRING(225) , allowNull: true},
    corstate :{type: DataTypes.STRING(225) , allowNull: true},
    corpin :{type: DataTypes.STRING(225) , allowNull: true},
    corcntry :{type: DataTypes.STRING(225) , allowNull: true},
    escoradd1 :{type: DataTypes.STRING(225) , allowNull: true},
    escoradd2 :{type: DataTypes.STRING(225) , allowNull: true},
    escoradd3 :{type: DataTypes.STRING(225) , allowNull: true},
    escoradd4 :{type: DataTypes.STRING(225) , allowNull: true},
    escorcity :{type: DataTypes.STRING(225) , allowNull: true},
    escorstate :{type: DataTypes.STRING(225) , allowNull: true},
    escorpin :{type: DataTypes.STRING(225) , allowNull: true},
    escorcntry :{type: DataTypes.STRING(225) , allowNull: true},
    closer_trf :{type: DataTypes.STRING(225) , allowNull: true},
    barcode :{type: DataTypes.STRING(225) , allowNull: true},
    brcd :{type: DataTypes.STRING(225) , allowNull: true},
    family_grp :{type: DataTypes.STRING(225) , allowNull: true},
    run_date :{type: DataTypes.STRING(225) , allowNull: true},
    

    
    // id: {type: DataTypes.INTEGER, allowNull: true , primaryKey: true,}
  };
  /* by default it pluralize the model, so it will tread it as 'People' and query will be like
     select * from People  (if you have pre existing table Person, then it won't get records)
  */
  const options = {
    freezeTableName: true,
    // don't add the timestamp attributes (updatedAt, createdAt)
    timestamps: false,
  };
  return sequelize.define("differences", attributes, options);
}
