const { DataTypes } = require("sequelize");

module.exports = model;

function model(sequelize) {
  const attributes = {
    Company_Code :{type: DataTypes.STRING(225) , allowNull: true},
Batch_Date :{type: DataTypes.DATE , allowNull: true},
APP_UPDTFLG :{type: DataTypes.STRING(225) , allowNull: true},
APP_POS_CODE :{type: DataTypes.STRING(225) , allowNull: true},
APP_TYPE :{type: DataTypes.STRING(225) , allowNull: true},
APP_NO :{type: DataTypes.STRING(225) , allowNull: true},
APP_DATE :{type: DataTypes.DATE , allowNull: true},
APP_PAN_NO :{type: DataTypes.STRING(225) , allowNull: true},
APP_PAN_COPY :{type: DataTypes.STRING(225) , allowNull: true},
APP_EXMT :{type: DataTypes.STRING(225) , allowNull: true},
APP_EXMT_CAT :{type: DataTypes.STRING(225) , allowNull: true},
APP_EXMT_ID_PROOF :{type: DataTypes.STRING(225) , allowNull: true},
APP_IPV_FLAG :{type: DataTypes.STRING(225) , allowNull: true},
APP_IPV_DATE :{type: DataTypes.DATE , allowNull: true},
APP_GEN :{type: DataTypes.STRING(225) , allowNull: true},
APP_NAME :{type: DataTypes.STRING(225) , allowNull: true},
APP_F_NAME :{type: DataTypes.STRING(225) , allowNull: true},
APP_REGNO :{type: DataTypes.STRING(225) , allowNull: true},
APP_DOB_INCORP :{type: DataTypes.DATE , allowNull: true},
APP_COMMENCE_DT :{type: DataTypes.DATE , allowNull: true},
APP_NATIONALITY :{type: DataTypes.STRING(225) , allowNull: true},
APP_OTH_NATIONALITY :{type: DataTypes.STRING(225) , allowNull: true},
APP_COMP_STATUS :{type: DataTypes.STRING(225) , allowNull: true},
APP_OTH_COMP_STATUS :{type: DataTypes.STRING(225) , allowNull: true},
APP_RES_STATUS :{type: DataTypes.STRING(225) , allowNull: true},
APP_RES_STATUS_PROOF :{type: DataTypes.STRING(225) , allowNull: true},
APP_UID_NO :{type: DataTypes.STRING(225) , allowNull: true},
APP_COR_ADD1 :{type: DataTypes.STRING(225) , allowNull: true},
APP_COR_ADD2 :{type: DataTypes.STRING(225) , allowNull: true},
APP_COR_ADD3 :{type: DataTypes.STRING(225) , allowNull: true},
APP_COR_CITY :{type: DataTypes.STRING(225) , allowNull: true},
APP_COR_PINCD :{type: DataTypes.STRING(225) , allowNull: true},
APP_COR_STATE :{type: DataTypes.STRING(225) , allowNull: true},
APP_COR_CTRY :{type: DataTypes.STRING(225) , allowNull: true},
APP_OFF_ISD :{type: DataTypes.STRING(225) , allowNull: true},
APP_OFF_STD :{type: DataTypes.STRING(225) , allowNull: true},
APP_OFF_NO :{type: DataTypes.STRING(225) , allowNull: true},
APP_RES_ISD :{type: DataTypes.STRING(225) , allowNull: true},
APP_RES_STD :{type: DataTypes.STRING(225) , allowNull: true},
APP_RES_NO :{type: DataTypes.STRING(225) , allowNull: true},
APP_MOB_ISD :{type: DataTypes.STRING(225) , allowNull: true},
APP_MOB_NO :{type: DataTypes.STRING(225) , allowNull: true},
APP_FAX_ISD :{type: DataTypes.STRING(225) , allowNull: true},
APP_FAX_STD :{type: DataTypes.STRING(225) , allowNull: true},
APP_FAX_NO :{type: DataTypes.STRING(225) , allowNull: true},
APP_EMAIL :{type: DataTypes.STRING(225) , allowNull: true},
APP_COR_ADD_PROOF :{type: DataTypes.STRING(225) , allowNull: true},
APP_COR_ADD_REF :{type: DataTypes.STRING(225) , allowNull: true},
APP_COR_ADD_DT :{type: DataTypes.DATE , allowNull: true},
APP_PER_ADD_FLAG :{type: DataTypes.STRING(225) , allowNull: true},
APP_PER_ADD1 :{type: DataTypes.STRING(225) , allowNull: true},
APP_PER_ADD2 :{type: DataTypes.STRING(225) , allowNull: true},
APP_PER_ADD3 :{type: DataTypes.STRING(225) , allowNull: true},
APP_PER_CITY :{type: DataTypes.STRING(225) , allowNull: true},
APP_PER_PINCD :{type: DataTypes.STRING(225) , allowNull: true},
APP_PER_STATE :{type: DataTypes.STRING(225) , allowNull: true},
APP_PER_CTRY :{type: DataTypes.STRING(225) , allowNull: true},
APP_PER_ADD_PROOF :{type: DataTypes.STRING(225) , allowNull: true},
APP_PER_ADD_REF :{type: DataTypes.STRING(225) , allowNull: true},
APP_PER_ADD_DT :{type: DataTypes.DATE , allowNull: true},
APP_INCOME :{type: DataTypes.STRING(225) , allowNull: true},
APP_OCC :{type: DataTypes.STRING(225) , allowNull: true},
APP_OTH_OCC :{type: DataTypes.STRING(225) , allowNull: true},
APP_POL_CONN :{type: DataTypes.STRING(225) , allowNull: true},
APP_DOC_PROOF :{type: DataTypes.STRING(225) , allowNull: true},
APP_INTERNAL_REF :{type: DataTypes.STRING(225) , allowNull: true},
APP_BRANCH_CODE :{type: DataTypes.STRING(225) , allowNull: true},
APP_MAR_STATUS :{type: DataTypes.STRING(225) , allowNull: true},
APP_NETWRTH :{type: DataTypes.FLOAT , allowNull: true},
APP_NETWORTH_DT :{type: DataTypes.DATE , allowNull: true},
APP_INCORP_PLC :{type: DataTypes.STRING(225) , allowNull: true},
APP_OTHERINFO :{type: DataTypes.STRING(225) , allowNull: true},
APP_ACC_OPENDT :{type: DataTypes.DATE , allowNull: true},
APP_ACC_ACTIVEDT :{type: DataTypes.DATE , allowNull: true},
APP_ACC_UPDTDT :{type: DataTypes.DATE , allowNull: true},
APP_PARENT :{type: DataTypes.STRING(225) , allowNull: true},
APP_FILLER1 :{type: DataTypes.STRING(225) , allowNull: true},
APP_FILLER2 :{type: DataTypes.STRING(225) , allowNull: true},
APP_FILLER3 :{type: DataTypes.STRING(225) , allowNull: true},
APP_CVLREFNO :{type: DataTypes.STRING(225) , allowNull: true},
APP_STATUS :{type: DataTypes.STRING(225) , allowNull: true},
APP_STATUSDT :{type: DataTypes.DATE , allowNull: true},
APP_ERROR_DESC :{type: DataTypes.STRING(225) , allowNull: true},
APP_DUMP_TYPE :{type: DataTypes.STRING(225) , allowNull: true},
APP_DNLDDT :{type: DataTypes.DATE , allowNull: true},
APP_REMARKS :{type: DataTypes.STRING(225) , allowNull: true},
APP_KYC_MODE :{type: DataTypes.STRING(225) , allowNull: true},
APP_VAULT_REF :{type: DataTypes.STRING(225) , allowNull: true},
APP_UID_TOKEN :{type: DataTypes.STRING(225) , allowNull: true},
APP_VER_NO :{type: DataTypes.STRING(225) , allowNull: true},
APP_ADDLDATA_UPDTFLG :{type: DataTypes.STRING(225) , allowNull: true},
APP_ENTITY_PAN :{type: DataTypes.STRING(225) , allowNull: true},
APP_ADDLDATA_PAN :{type: DataTypes.STRING(225) , allowNull: true},
APP_ADDLDATA_NAME :{type: DataTypes.STRING(225) , allowNull: true},
APP_ADDLDATA_DIN_UID :{type: DataTypes.STRING(225) , allowNull: true},
APP_ADDLDATA_RELATIONSHIP :{type: DataTypes.STRING(225) , allowNull: true},
APP_ADDLDATA_POLCONN :{type: DataTypes.STRING(225) , allowNull: true},
APP_ADDLDATA_FILLER1 :{type: DataTypes.STRING(225) , allowNull: true},
APP_ADDLDATA_FILLER2 :{type: DataTypes.STRING(225) , allowNull: true},
APP_ADDLDATA_FILLER3 :{type: DataTypes.STRING(225) , allowNull: true},
ADDL_CVLREFNO :{type: DataTypes.STRING(225) , allowNull: true},
APP_ADDLDATA_STATUS :{type: DataTypes.STRING(225) , allowNull: true},
APP_ADDLDATA_STATUSDT :{type: DataTypes.DATE , allowNull: true},
APP_ADDLDATA_ERROR_DESC :{type: DataTypes.STRING(225) , allowNull: true},
ADDL_DUMP_TYPE :{type: DataTypes.STRING(225) , allowNull: true},
ADDL_DNLDDT :{type: DataTypes.DATE , allowNull: true},
NO_OF_KYC_RECORDS :{type: DataTypes.INTEGER , allowNull: true},
NO_OF_ADDLDATA_RECORDS :{type: DataTypes.INTEGER , allowNull: true},

  };
  /* by default it pluralize the model, so it will tread it as 'People' and query will be like
     select * from People  (if you have pre existing table Person, then it won't get records)
  */
  const options = {
    freezeTableName: true,
    // don't add the timestamp attributes (updatedAt, createdAt)
    timestamps: false,
  };
  return sequelize.define("CombinedData", attributes, options);
}
