const { DataTypes } = require("sequelize");

module.exports = model;

function model(sequelize) {
  const attributes = {
    // Id: {
    //   type: DataTypes.INTEGER,
    //   allowNull: true,
    //   autoIncrement: true,
    //   primaryKey: true,
    // },
    priority :{type: DataTypes.STRING(225) , allowNull: true},
ac_closed :{type: DataTypes.STRING(225) , allowNull: true},
closer_trf :{type: DataTypes.STRING(225) , allowNull: true},
ems_ddt :{type: DataTypes.STRING(225) , allowNull: true},
nod_dormnt :{type: DataTypes.STRING(225) , allowNull: true},
barcode :{type: DataTypes.STRING(225) , allowNull: true},
brcd :{type: DataTypes.STRING(225) , allowNull: true},
ucc :{type: DataTypes.STRING(225) , allowNull: true},
kslucc :{type: DataTypes.STRING(225) , allowNull: true},
clname :{type: DataTypes.STRING(225) , allowNull: true},
ks_krasts :{type: DataTypes.STRING(225) , allowNull: true},
ks_pttsts :{type: DataTypes.STRING(225) , allowNull: true},
ks_kusts :{type: DataTypes.STRING(225) , allowNull: true},
ks_krarem :{type: DataTypes.STRING(225) , allowNull: true},
ks_emsent :{type: DataTypes.STRING(225) , allowNull: true},
ks_emrecd :{type: DataTypes.STRING(225) , allowNull: true},
ks_eslrm :{type: DataTypes.STRING(225) , allowNull: true},
ks_ltstrm :{type: DataTypes.STRING(225) , allowNull: true},
sts1_3i :{type: DataTypes.STRING(225) , allowNull: true},
sts2_3i :{type: DataTypes.STRING(225) , allowNull: true},
ks_othsts :{type: DataTypes.STRING(225) , allowNull: true},
mult_emmo :{type: DataTypes.STRING(225) , allowNull: true},
ks_sts1 :{type: DataTypes.STRING(225) , allowNull: true},
ks_allrem :{type: DataTypes.STRING(225) , allowNull: true},
es_dobdoi :{type: DataTypes.STRING(225) , allowNull: true},
catg :{type: DataTypes.STRING(225) , allowNull: true},
panno :{type: DataTypes.STRING(225) , allowNull: true},
neoid :{type: DataTypes.STRING(225) , allowNull: true},
odinid :{type: DataTypes.STRING(225) , allowNull: true},
bossid :{type: DataTypes.STRING(225) , allowNull: true},
cl_frboss :{type: DataTypes.STRING(225) , allowNull: true},
ks_mtfcl :{type: DataTypes.STRING(225) , allowNull: true},
locationid :{type: DataTypes.STRING(225) , allowNull: true},
es_locncd :{type: DataTypes.STRING(225) , allowNull: true},
es_locnid :{type: DataTypes.STRING(225) , allowNull: true},
eckyc_no :{type: DataTypes.STRING(225) , allowNull: true},
k_platform :{type: DataTypes.STRING(225) , allowNull: true},
ks_clusrid :{type: DataTypes.STRING(225) , allowNull: true},
ks_ralfno :{type: DataTypes.STRING(225) , allowNull: true},
ks_ralncm :{type: DataTypes.STRING(225) , allowNull: true},
ks_dpid :{type: DataTypes.STRING(225) , allowNull: true},
ks_dpboid :{type: DataTypes.STRING(225) , allowNull: true},
es_nodpac :{type: DataTypes.STRING(225) , allowNull: true},
esdp_map :{type: DataTypes.STRING(225) , allowNull: true},
es_dpboid :{type: DataTypes.STRING(225) , allowNull: true},
ks_dprtcd :{type: DataTypes.STRING(225) , allowNull: true},
dp_ratecd :{type: DataTypes.STRING(225) , allowNull: true},
ks_nomn :{type: DataTypes.STRING(225) , allowNull: true},
ks_relwapc :{type: DataTypes.STRING(225) , allowNull: true},
es_nomn :{type: DataTypes.STRING(225) , allowNull: true},
es_relwapc :{type: DataTypes.STRING(225) , allowNull: true},
ks_clsts :{type: DataTypes.STRING(225) , allowNull: true},
es_clsts :{type: DataTypes.STRING(225) , allowNull: true},
bo_clsts :{type: DataTypes.STRING(225) , allowNull: true},
ks_nsecm :{type: DataTypes.STRING(225) , allowNull: true},
es_nsecm :{type: DataTypes.STRING(225) , allowNull: true},
is_mtchncm :{type: DataTypes.STRING(225) , allowNull: true},
ks_bsecm :{type: DataTypes.STRING(225) , allowNull: true},
es_bsecm :{type: DataTypes.STRING(225) , allowNull: true},
is_mtchbcm :{type: DataTypes.STRING(225) , allowNull: true},
ks_nsefo :{type: DataTypes.STRING(225) , allowNull: true},
es_nsefo :{type: DataTypes.STRING(225) , allowNull: true},
is_mtchnfo :{type: DataTypes.STRING(225) , allowNull: true},
ks_nsecds :{type: DataTypes.STRING(225) , allowNull: true},
es_nsecds :{type: DataTypes.STRING(225) , allowNull: true},
is_mtchcds :{type: DataTypes.STRING(225) , allowNull: true},
ks_mcx :{type: DataTypes.STRING(225) , allowNull: true},
es_mcx :{type: DataTypes.STRING(225) , allowNull: true},
is_mtchmcx :{type: DataTypes.STRING(225) , allowNull: true},
ks_ncdex :{type: DataTypes.STRING(225) , allowNull: true},
es_ncdex :{type: DataTypes.STRING(225) , allowNull: true},
is_mtchncd :{type: DataTypes.STRING(225) , allowNull: true},
ks_emtocl :{type: DataTypes.STRING(225) , allowNull: true},
ks_esign :{type: DataTypes.STRING(225) , allowNull: true},
ks_essts :{type: DataTypes.STRING(225) , allowNull: true},
ks_emailid :{type: DataTypes.STRING(225) , allowNull: true},
es_email :{type: DataTypes.STRING(225) , allowNull: true},
is_mtch_em :{type: DataTypes.STRING(225) , allowNull: true},
ks_emrel :{type: DataTypes.STRING(225) , allowNull: true},
es_emrel :{type: DataTypes.STRING(225) , allowNull: true},
ks_mobile :{type: DataTypes.STRING(225) , allowNull: true},
es_mobile :{type: DataTypes.STRING(225) , allowNull: true},
is_mtch_mo :{type: DataTypes.STRING(225) , allowNull: true},
ks_mobrel :{type: DataTypes.STRING(225) , allowNull: true},
es_mobrel :{type: DataTypes.STRING(225) , allowNull: true},
estovr :{type: DataTypes.STRING(225) , allowNull: true},
es_netbkg :{type: DataTypes.STRING(225) , allowNull: true},
ks_lstrdt :{type: DataTypes.STRING(225) , allowNull: true},
es_lstrdt :{type: DataTypes.STRING(225) , allowNull: true},
es_mtfpos :{type: DataTypes.STRING(225) , allowNull: true},
es_opnpos :{type: DataTypes.STRING(225) , allowNull: true},
es_margin :{type: DataTypes.STRING(225) , allowNull: true},
es_ledbal :{type: DataTypes.STRING(225) , allowNull: true},
es_dpledg :{type: DataTypes.STRING(225) , allowNull: true},
es_dphldg :{type: DataTypes.STRING(225) , allowNull: true},
es_ccol :{type: DataTypes.STRING(225) , allowNull: true},
es_nccol :{type: DataTypes.STRING(225) , allowNull: true},
es_pledval :{type: DataTypes.STRING(225) , allowNull: true},
es_corpact :{type: DataTypes.STRING(225) , allowNull: true},
es_pfreco :{type: DataTypes.STRING(225) , allowNull: true},
brname :{type: DataTypes.STRING(225) , allowNull: true},
family_grp :{type: DataTypes.STRING(225) , allowNull: true},
run_date :{type: DataTypes.STRING(225) , allowNull: true},
ks_emtrgdt :{type: DataTypes.STRING(225) , allowNull: true},
es_rem1kc :{type: DataTypes.STRING(225) , allowNull: true},
es_rem2pp :{type: DataTypes.STRING(225) , allowNull: true},

ksl_date :{type: DataTypes.STRING(225) , allowNull: true},
ksl_status :{type: DataTypes.STRING(225) , allowNull: true},
kslstatus :{type: DataTypes.STRING(225) , allowNull: true},
ksl_remk :{type: DataTypes.STRING(225) , allowNull: true},



status :{type: DataTypes.STRING(225) , allowNull: true},
updstatus :{type: DataTypes.STRING(225) , allowNull: true},
statusdate :{type: DataTypes.STRING(225) , allowNull: true},
updstatusdate :{type: DataTypes.STRING(225) , allowNull: true},


date :{type: DataTypes.STRING(225) , allowNull: true},
describe :{type: DataTypes.STRING(225) , allowNull: true},
result :{type: DataTypes.STRING(225) , allowNull: true},




    // id: {type: DataTypes.INTEGER, allowNull: true , primaryKey: true,}
  };
  /* by default it pluralize the model, so it will tread it as 'People' and query will be like
     select * from People  (if you have pre existing table Person, then it won't get records)
  */
  const options = {
    freezeTableName: true,
    // don't add the timestamp attributes (updatedAt, createdAt)
    timestamps: false,
  };
  return sequelize.define("details", attributes, options);
}
