const { DataTypes } = require("sequelize");

module.exports = model;

function model(sequelize) {
  const attributes = {
    client_code :{type: DataTypes.STRING(225) , allowNull: true},
cl_name :{type: DataTypes.STRING(225) , allowNull: true},
Clientlocation :{type: DataTypes.STRING(225) , allowNull: true},
Client_vertical :{type: DataTypes.STRING(225) , allowNull: true},
record_id :{type: DataTypes.FLOAT , allowNull: true},
amd_user_id :{type: DataTypes.FLOAT , allowNull: true},
amd_session_id :{type: DataTypes.FLOAT , allowNull: true},
trade_date :{type: DataTypes.STRING(225) , allowNull: true},
accumulation_ref_no :{type: DataTypes.FLOAT , allowNull: true},
session_id :{type: DataTypes.FLOAT , allowNull: true},
contract_no :{type: DataTypes.FLOAT , allowNull: true},
contract_type :{type: DataTypes.STRING(225) , allowNull: true},
exchange_code :{type: DataTypes.STRING(225) , allowNull: true},
series_id :{type: DataTypes.FLOAT , allowNull: true},
instrument_type :{type: DataTypes.STRING(225) , allowNull: true},
market_type :{type: DataTypes.STRING(225) , allowNull: true},
stock_name :{type: DataTypes.STRING(225) , allowNull: true},
exp_date :{type: DataTypes.STRING(225) , allowNull: true},
option_type :{type: DataTypes.STRING(225) , allowNull: true},
option_style :{type: DataTypes.STRING(225) , allowNull: true},
strike_price :{type: DataTypes.FLOAT , allowNull: true},
fut_opt_flag :{type: DataTypes.STRING(225) , allowNull: true},
expiry_date :{type: DataTypes.FLOAT , allowNull: true},
trade_no :{type: DataTypes.STRING(225) , allowNull: true},
trade_time :{type: DataTypes.FLOAT , allowNull: true},
order_no :{type: DataTypes.STRING(225) , allowNull: true},
order_time :{type: DataTypes.FLOAT , allowNull: true},
trade_type :{type: DataTypes.FLOAT , allowNull: true},
trade_quantity :{type: DataTypes.STRING(225) , allowNull: true},
lot_size :{type: DataTypes.FLOAT , allowNull: true},
market_rate :{type: DataTypes.FLOAT , allowNull: true},
confirmed_market_rate :{type: DataTypes.FLOAT , allowNull: true},
brokerage_per_unit :{type: DataTypes.FLOAT , allowNull: true},
service_tax_per_unit :{type: DataTypes.FLOAT , allowNull: true},
net_rate :{type: DataTypes.FLOAT , allowNull: true},
squp_delv_flag :{type: DataTypes.FLOAT , allowNull: true},
open_position_flag :{type: DataTypes.FLOAT , allowNull: true},
trade_status :{type: DataTypes.FLOAT , allowNull: true},
trade_flag :{type: DataTypes.STRING(225) , allowNull: true},
ccf_flag :{type: DataTypes.FLOAT , allowNull: true},
execute_flag :{type: DataTypes.FLOAT , allowNull: true},
auto_expired :{type: DataTypes.FLOAT , allowNull: true},
participant_code :{type: DataTypes.STRING(225) , allowNull: true},
backoffice_code :{type: DataTypes.STRING(225) , allowNull: true},
alias_code :{type: DataTypes.STRING(225) , allowNull: true},
terminal_id :{type: DataTypes.FLOAT , allowNull: true},
client_type :{type: DataTypes.STRING(225) , allowNull: true},
isin_code :{type: DataTypes.STRING(225) , allowNull: true},
original_trade :{type: DataTypes.FLOAT , allowNull: true},
process_status :{type: DataTypes.FLOAT , allowNull: true},
premium_turnover :{type: DataTypes.FLOAT , allowNull: true},
strike_turnover :{type: DataTypes.FLOAT , allowNull: true},
strike_premium_turnover :{type: DataTypes.FLOAT , allowNull: true},
clientwise_turnover :{type: DataTypes.FLOAT , allowNull: true},
contractwise_turnover :{type: DataTypes.FLOAT , allowNull: true},
original_trade_date :{type: DataTypes.STRING(225) , allowNull: true},
scrip_weighted_rate :{type: DataTypes.FLOAT , allowNull: true},
profit_loss_amount :{type: DataTypes.FLOAT , allowNull: true},
contract_market_rate_digits :{type: DataTypes.FLOAT , allowNull: true},
contract_brokerage_digits :{type: DataTypes.FLOAT , allowNull: true},
market_rate_round_truncate :{type: DataTypes.FLOAT , allowNull: true},
brokerage_round_truncate :{type: DataTypes.FLOAT , allowNull: true},
contract_market_value :{type: DataTypes.FLOAT , allowNull: true},
contract_net_value :{type: DataTypes.FLOAT , allowNull: true},
trade_source :{type: DataTypes.FLOAT , allowNull: true},
uploaded_net_rate :{type: DataTypes.FLOAT , allowNull: true},
parent_record_id :{type: DataTypes.FLOAT , allowNull: true},
amd_date :{type: DataTypes.STRING(225) , allowNull: true},
squp_delv_flag_satellite :{type: DataTypes.FLOAT , allowNull: true},
brokerage_per_unit_original :{type: DataTypes.FLOAT , allowNull: true},
exclusion_flag :{type: DataTypes.FLOAT , allowNull: true},
locnid :{type: DataTypes.STRING(225) , allowNull: true},


  };
  /* by default it pluralize the model, so it will tread it as 'People' and query will be like
     select * from People  (if you have pre existing table Person, then it won't get records)
  */
  const options = {
    freezeTableName: true,
    // don't add the timestamp attributes (updatedAt, createdAt)
    timestamps: false,
  };
  return sequelize.define("saudabookdev", attributes, options);
}
